### ISSUE TITLE
Rasa CLI: Server interaction

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa_nlu#3067]
Based on https://github.com/RasaHQ/rasa_stack/issues/1:

Already done:
* Training: `rasa train`, `rasa train core`, `rasa train nlu`
* Testing: `rasa test`, `rasa test core`, `rasa test nlu`
* Show: `rasa show stories`
* Running: `rasa run`, `rasa run core`, `rasa run nlu`, `rasa run actions`, `rasa shell`, `rasa interactive`
* Data: `rasa data split nlu`, `rasa data convert nlu`
* Other: `rasa --version`

### Crucial
- [ ] provide credentials: `rasa remote login <host>` (where / how do we store them)
- [ ] select environment (prod / dev / test): `rasa remote stages <env>`
- [ ] set model as active: `rasa remote models select <model-id>`
- [ ] pushing models:  `rasa remote models push <model>`
- [ ] downloading models: `rasa remote models pull <model>`
- [ ] push data: `rasa remote data push`
- [ ] pull data: `rasa remote data pull`

### Nice to have
- [ ] list models: `rasa remote models list`
- [ ]  list users: `rasa remote users list`
- [ ] status : `rasa remote status`
- [ ] logs: `rasa remote logs`
- [ ] show config: `rasa remote config`

## Todo 2: Local server interaction
`rasa local`
commands as above for server except
* no login
* pushing / downloading are not needed (set as active should be enough)

### Crucial
- [ ] provide credentials: `rasa local login <host>` (where / how do we store them)
- [ ] select environment (prod / dev / test): `rasa local stages <env>`
- [ ] set model as active: `rasa local models select <model-id>`
- [ ] pushing models:  `rasa local models push <model>`
- [ ] downloading models: `rasa local models pull <model>`
- [ ] push data: `rasa local data push`
- [ ] pull data: `rasa local data pull`

### Nice to have
- [ ] list models: `rasa local models list`
- [ ]  list users: `rasa local users list`
- [ ] status : `rasa local status`
- [ ] logs: `rasa local logs`
- [ ] show config: `rasa local config`

## Todo 3: Documentation
- [ ] Documentation

**Comment by wochinge** [comment]
Issue moved to [RasaHQ/roadmap #429](https://github.com/RasaHQ/roadmap/issues/429) via [**ZenHub**](https://www.zenhub.com/)
